version: '3'
services:

  # PostgreSQL
  # db:
  #   image: postgres:9.5
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: redmine
  #   # ports:
  #   #   - 5432:5432
  #   # volumes:
  #   #   - ./db/postgres:/var/lib/postgresql/data

  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
      # MYSQL_PASSWORD: password
      # MYSQL_USER: redmine
    # ports:
    #   - 3306:3306
    # volumes:
    #   - ./db/mysql:/var/lib/mysql
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  app:
    build:
      context: .
      args:
        RAILS_DB_ADAPTER: mysql2
    environment:
      # RAILS_DB_ADAPTER: postgresql
      RAILS_DB_ADAPTER: mysql2
      RAILS_DB_HOST: db
      RAILS_DB: redmine
      # RAILS_DB_USERNAME: redmine
      RAILS_DB_USERNAME: root
      RAILS_DB_PASSWORD: password
      RAILS_DB_ENCODING: utf8
      RAILS_ENV: development
      # SECRET_KEY_BASE: e4a046de71177a72ff251013cc10924db7673c19497d6fe9c463ab8c43f5d71fc1509891aea726cc3e6f32c78bb8fdca0f4b1834e8502964e2f187aff90ea307

      REDMINE_MAIL_DELIVERY_METHOD: smtp
      REDMINE_MAIL_ADDRESS: localhost
      REDMINE_MAIL_PORT: 25
      REDMINE_MAIL_DOMAIN: example.com
      REDMINE_IMAGEMGICK_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

    ports: 
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/var/lib/redmine