version: '3'
services:

  # PostgreSQL
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: redmine
    # ports:
    #   - 5432:5432
    # volumes:
    #   - ./db/postgres:/var/lib/postgresql/data

  app:
    build: .
    environment:
      RAILS_DB_HOST: db
      RAILS_DB: redmine
      RAILS_DB_USERNAME: redmine
      RAILS_DB_PASSWORD: password
      RAILS_DB_ENCODING: utf8
      RAILS_ENV: development

      REDMINE_MAIL_DELIVERY_METHOD: smtp
      REDMINE_MAIL_ADDRESS: localhost
      REDMINE_MAIL_PORT: 25
      REDMINE_MAIL_DOMAIN: example.com
      REDMINE_IMAGEMGICK_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      S3_BUCKET_NAME: 
      S3_FOLDER_NAME: files
      S3_ENDPOINT: s3.amazonaws.com

    ports: 
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/var/lib/redmine
      
# volumes:
#   redmine_data:
#     driver: local
#   postgres_data:
#     driver: local
