kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redmine-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: pv-redmine